language: python
sudo: false
addons:
  apt_packages:
  - pandoc
python:
- '3.5'
- '3.6'
install:
- python setup.py install
- pip install pycodestyle mypy pypandoc typing
script:
- pycodestyle --first midori
- mypy --py2 midori
- python setup.py test --addopts "--cov midori tests"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davetcode
  password:
    secure: FJ7f1bJGn2PZK+xX8oiSO9LmpvpnuyaJEH/cQ6X2dPbUqQJc0iz77nU1f1j40nulyu/8xciPnUNoFH6MD7EDSk8gZlFZ/i9mzYdH2l8iNjzD2yGZX0ReRXibfPtrPPm5cn8OUOIFZJdHffXyFbBL2TttXB/XZmVNlaqZdhYbO3/ui/D/fPCbdbV9AbiHSeRCNbK7TYBM7Ju2B5dOmaHHeVyq25moBC/3P63AE1KRAt/2jaHRbPCeBQKZyDSAcOc6Kj0zNAgjgi+lS2LRQPpsC4GW4NgoNYkTLDqul2fsCOvNVU0SqR1Ca6/KuCvna369l1QYKAcl/v0v4ZQpuyGC7Lolb8y814vrHzcEzSZhjTC/OpKOuH5C6Ql98YYSzObmFVE1fUj1rJEJMs2W7n3gpQvhjLv9ekGKFdMNqY4aLVsQA4Ch0VljYObxzX9zmVdY8vBFbfb/QChUXCBHyQ7m2WD7urohqTSpFPZzKV1t/6weZmxtOPKz+FcDD1Z6/ganhlnRleT3Go9SsG+QTBfLdB7tJ6dPBJgCyGXVds4l0OP3cmuFjDE5cJHX8Tlx+p1lihpuqNO1dqhM8TxqzJwewABIVVZpgYp4XRU1kKaEZYlm1TRNlnBNp8yAiSEdsE+coisIzy8bUW9YBdfFBBq2AL86cCho0VTfmDdlfsh0tPM=
  on:
    tags: true
    repo: DaveTCode/confluence-archiving-python-lib
    condition: "$TRAVIS_PYTHON_VERSION == 3.6 && $TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$"
